window.LISAN_COURSES = window.LISAN_COURSES || {};
window.LISAN_COURSES.cmn = {
  id: "cmn",
  intro: "Mandarin grammar is refreshingly simple — no conjugation, no plurals, no tenses. The challenge is tones and characters. Pinyin is shown everywhere; focus on tones from day one.",
  units: [
    {
      id: "u1", title: "First Contact", level: "A0",
      notes: [
        { title: "The four tones", cat: "pronunciation",
          body: "mā (high flat) má (rising) mǎ (dip-rise) mà (falling) — four different words! Tone is part of the word, like a vowel. Practice exaggerating tones; native speakers prefer exaggerated-but-correct over flat.",
          examples: [{ t: "妈 mā / 马 mǎ / 骂 mà", en: "mom / horse / to scold" }] },
        { title: "你好 and beyond", cat: "greetings",
          body: "你好 (nǐ hǎo) is the safe hello. 您好 (nín hǎo) is polite/formal. Real-life friends often greet by asking 吃了吗? (have you eaten?).",
          examples: [{ t: "您好", r: "nín hǎo", en: "hello (polite)" }] },
      ],
      vocab: [
        { t: "你好", r: "nǐ hǎo", en: "hello", cats: ["greetings"] },
        { t: "再见", r: "zàijiàn", en: "goodbye", cats: ["greetings"] },
        { t: "早上好", r: "zǎoshang hǎo", en: "good morning", cats: ["greetings"] },
        { t: "晚安", r: "wǎn'ān", en: "good night", cats: ["greetings"] },
        { t: "请", r: "qǐng", en: "please", cats: ["politeness"] },
        { t: "谢谢", r: "xièxie", en: "thank you", cats: ["politeness"] },
        { t: "是", r: "shì", en: "yes / to be", cats: ["vocabulary", "verbs"] },
        { t: "不", r: "bù", en: "no / not", cats: ["vocabulary", "negation"] },
        { t: "对不起", r: "duìbuqǐ", en: "sorry", cats: ["politeness"] },
        { t: "我叫...", r: "wǒ jiào...", en: "my name is...", cats: ["greetings"] },
      ],
      sentences: [
        { t: "你好，我叫小明。", r: "nǐ hǎo, wǒ jiào Xiǎomíng", en: "Hello, my name is Xiaoming.", cats: ["greetings"], tok: ["你好", "，", "我", "叫", "小明", "。"] },
        { t: "很高兴认识你。", r: "hěn gāoxìng rènshi nǐ", en: "Nice to meet you.", cats: ["greetings", "wordorder"], tok: ["很", "高兴", "认识", "你", "。"] },
        { t: "你叫什么名字？", r: "nǐ jiào shénme míngzi?", en: "What is your name?", cats: ["questions"], tok: ["你", "叫", "什么", "名字", "？"] },
        { t: "非常感谢。", r: "fēicháng gǎnxiè", en: "Thank you very much.", cats: ["politeness"], tok: ["非常", "感谢", "。"] },
      ],
      dialogue: { title: "Meeting someone", turns: [
        { s: "A", t: "你好！你叫什么名字？", r: "nǐ hǎo! nǐ jiào shénme míngzi?", en: "Hi! What's your name?" },
        { s: "B", t: "我叫李华。你呢？", r: "wǒ jiào Lǐ Huá. nǐ ne?", en: "My name is Li Hua. And you?" },
        { s: "A", t: "我叫王明。很高兴认识你。", r: "wǒ jiào Wáng Míng. hěn gāoxìng rènshi nǐ", en: "I'm Wang Ming. Nice to meet you." },
        { s: "B", t: "我也是。再见！", r: "wǒ yě shì. zàijiàn!", en: "Me too. Bye!" },
      ]},
    },
    {
      id: "u2", title: "People & Pronouns", level: "A1",
      notes: [
        { title: "Pronouns — beautifully simple", cat: "pronouns",
          body: "我 wǒ (I), 你 nǐ (you), 他/她 tā (he/she — same sound!), 我们 wǒmen (we), 他们 tāmen (they). Just add 们 (men) for plural. No cases, no conjugation.",
          examples: [{ t: "我们是朋友。", r: "wǒmen shì péngyou", en: "We are friends." }] },
        { title: "的 (de) — possession", cat: "particles",
          body: "的 links owner and thing: 我的妈妈 (wǒ de māma) = my mom. With close relationships 的 often drops: 我妈妈.",
          examples: [{ t: "我的朋友", r: "wǒ de péngyou", en: "my friend" }] },
      ],
      vocab: [
        { t: "我", r: "wǒ", en: "I", cats: ["pronouns"] },
        { t: "你", r: "nǐ", en: "you", cats: ["pronouns"] },
        { t: "他", r: "tā", en: "he", cats: ["pronouns"] },
        { t: "她", r: "tā", en: "she", cats: ["pronouns"] },
        { t: "我们", r: "wǒmen", en: "we", cats: ["pronouns"] },
        { t: "家人", r: "jiārén", en: "family", cats: ["nouns"] },
        { t: "妈妈", r: "māma", en: "mom", cats: ["nouns"] },
        { t: "爸爸", r: "bàba", en: "dad", cats: ["nouns"] },
        { t: "朋友", r: "péngyou", en: "friend", cats: ["nouns"] },
        { t: "谁", r: "shéi", en: "who", cats: ["questions"] },
      ],
      sentences: [
        { t: "我是北京人。", r: "wǒ shì Běijīng rén", en: "I am from Beijing.", cats: ["verbs", "wordorder"], tok: ["我", "是", "北京", "人", "。"] },
        { t: "她是我妈妈。", r: "tā shì wǒ māma", en: "She is my mom.", cats: ["verbs", "particles"], tok: ["她", "是", "我", "妈妈", "。"] },
        { t: "这是谁？", r: "zhè shì shéi?", en: "Who is this?", cats: ["questions"], tok: ["这", "是", "谁", "？"] },
        { t: "我们是朋友。", r: "wǒmen shì péngyou", en: "We are friends.", cats: ["verbs", "wordorder"], tok: ["我们", "是", "朋友", "。"] },
      ],
      dialogue: { title: "Family photo", turns: [
        { s: "A", t: "这是谁？", r: "zhè shì shéi?", en: "Who is this?" },
        { s: "B", t: "这是我妈妈。她叫王丽。", r: "zhè shì wǒ māma. tā jiào Wáng Lì", en: "This is my mom. Her name is Wang Li." },
        { s: "A", t: "这是你爸爸吗？", r: "zhè shì nǐ bàba ma?", en: "Is this your dad?" },
        { s: "B", t: "是，这是我爸爸。", r: "shì, zhè shì wǒ bàba", en: "Yes, this is my dad." },
      ]},
    },
    {
      id: "u3", title: "Numbers & Time", level: "A1",
      notes: [
        { title: "Numbers 1–10", cat: "numbers",
          body: "一 yī, 二 èr, 三 sān, 四 sì, 五 wǔ, 六 liù, 七 qī, 八 bā, 九 jiǔ, 十 shí. Everything stacks: 11 = 十一, 20 = 二十, 25 = 二十五. Learn 10 words, count to 99!",
          examples: [{ t: "二十五", r: "èrshíwǔ", en: "25 (two-ten-five)" }] },
        { title: "Time: 点 (diǎn)", cat: "numbers",
          body: "现在几点? (xiànzài jǐ diǎn?) = What time is it now? Answer: number + 点: 三点 = 3 o'clock, 三点半 = 3:30 (半 = half).",
          examples: [{ t: "现在三点半。", r: "xiànzài sān diǎn bàn", en: "It's 3:30 now." }] },
      ],
      vocab: [
        { t: "一", r: "yī", en: "one", cats: ["numbers"] },
        { t: "二", r: "èr", en: "two", cats: ["numbers"] },
        { t: "三", r: "sān", en: "three", cats: ["numbers"] },
        { t: "五", r: "wǔ", en: "five", cats: ["numbers"] },
        { t: "十", r: "shí", en: "ten", cats: ["numbers"] },
        { t: "今天", r: "jīntiān", en: "today", cats: ["vocabulary", "numbers"] },
        { t: "明天", r: "míngtiān", en: "tomorrow", cats: ["vocabulary", "numbers"] },
        { t: "点", r: "diǎn", en: "o'clock", cats: ["numbers"] },
        { t: "星期一", r: "xīngqīyī", en: "Monday", cats: ["numbers"] },
        { t: "星期", r: "xīngqī", en: "week", cats: ["nouns", "numbers"] },
      ],
      sentences: [
        { t: "现在几点？", r: "xiànzài jǐ diǎn?", en: "What time is it now?", cats: ["questions", "numbers"], tok: ["现在", "几", "点", "？"] },
        { t: "现在五点。", r: "xiànzài wǔ diǎn", en: "It's five o'clock.", cats: ["numbers"], tok: ["现在", "五", "点", "。"] },
        { t: "今天星期一。", r: "jīntiān xīngqīyī", en: "Today is Monday.", cats: ["numbers", "wordorder"], tok: ["今天", "星期一", "。"] },
        { t: "我有两个哥哥。", r: "wǒ yǒu liǎng ge gēge", en: "I have two older brothers.", cats: ["numbers", "particles"], tok: ["我", "有", "两", "个", "哥哥", "。"] },
      ],
      dialogue: { title: "Making a plan", turns: [
        { s: "A", t: "现在几点？", r: "xiànzài jǐ diǎn?", en: "What time is it?" },
        { s: "B", t: "四点半。", r: "sì diǎn bàn", en: "Half past four." },
        { s: "A", t: "我们明天十点见，好吗？", r: "wǒmen míngtiān shí diǎn jiàn, hǎo ma?", en: "Shall we meet tomorrow at ten?" },
        { s: "B", t: "好，明天见！", r: "hǎo, míngtiān jiàn!", en: "OK, see you tomorrow!" },
      ]},
    },
    {
      id: "u4", title: "Food & Ordering", level: "A1",
      notes: [
        { title: "我要 / 我想要 — ordering", cat: "politeness",
          body: "我要... (wǒ yào) = I want (direct, fine in restaurants). 我想要... (wǒ xiǎng yào) = I would like (softer). Add 请 for extra politeness.",
          examples: [{ t: "我要一杯咖啡。", r: "wǒ yào yì bēi kāfēi", en: "I want a cup of coffee." }] },
        { title: "Measure words", cat: "particles",
          body: "Numbers need a measure word before nouns: 一杯咖啡 (one CUP-OF coffee), 两个人 (two GE people). 个 (ge) is the universal fallback.",
          examples: [{ t: "三个朋友", r: "sān ge péngyou", en: "three friends" }] },
      ],
      vocab: [
        { t: "水", r: "shuǐ", en: "water", cats: ["nouns"] },
        { t: "咖啡", r: "kāfēi", en: "coffee", cats: ["nouns"] },
        { t: "茶", r: "chá", en: "tea", cats: ["nouns"] },
        { t: "米饭", r: "mǐfàn", en: "rice", cats: ["nouns"] },
        { t: "吃", r: "chī", en: "to eat", cats: ["verbs"] },
        { t: "喝", r: "hē", en: "to drink", cats: ["verbs"] },
        { t: "要", r: "yào", en: "to want", cats: ["verbs"] },
        { t: "买单", r: "mǎidān", en: "the bill (to pay)", cats: ["nouns"] },
        { t: "好吃", r: "hǎochī", en: "delicious", cats: ["vocabulary"] },
        { t: "饭馆", r: "fànguǎn", en: "restaurant", cats: ["nouns"] },
      ],
      sentences: [
        { t: "我要一杯咖啡。", r: "wǒ yào yì bēi kāfēi", en: "I want a cup of coffee.", cats: ["particles", "wordorder"], tok: ["我", "要", "一", "杯", "咖啡", "。"] },
        { t: "你想吃什么？", r: "nǐ xiǎng chī shénme?", en: "What do you want to eat?", cats: ["questions", "verbs"], tok: ["你", "想", "吃", "什么", "？"] },
        { t: "很好吃！", r: "hěn hǎochī!", en: "Very delicious!", cats: ["vocabulary"], tok: ["很", "好吃", "！"] },
        { t: "买单，谢谢。", r: "mǎidān, xièxie", en: "The bill, thanks.", cats: ["politeness"], tok: ["买单", "，", "谢谢", "。"] },
      ],
      dialogue: { title: "At a restaurant", turns: [
        { s: "A", t: "你好，你要什么？", r: "nǐ hǎo, nǐ yào shénme?", en: "Hello, what would you like?" },
        { s: "B", t: "我要米饭和茶。", r: "wǒ yào mǐfàn hé chá", en: "I want rice and tea." },
        { s: "A", t: "还要别的吗？", r: "hái yào biéde ma?", en: "Anything else?" },
        { s: "B", t: "不要了，谢谢。买单。", r: "bú yào le, xièxie. mǎidān", en: "Nothing else, thanks. The bill." },
      ]},
    },
    {
      id: "u5", title: "Daily Verbs", level: "A1+",
      notes: [
        { title: "No conjugation — particles mark time", cat: "verbs",
          body: "Verbs never change: 我吃 (I eat), 他吃 (he eats). 了 (le) marks completion: 我吃了 = I ate. 在 (zài) marks ongoing: 我在吃 = I'm eating. Negate with 不 (bù) or 没 (méi, for past).",
          examples: [{ t: "我不吃肉。", r: "wǒ bù chī ròu", en: "I don't eat meat." }] },
      ],
      vocab: [
        { t: "说", r: "shuō", en: "to speak", cats: ["verbs"] },
        { t: "工作", r: "gōngzuò", en: "to work / job", cats: ["verbs", "nouns"] },
        { t: "学习", r: "xuéxí", en: "to study", cats: ["verbs"] },
        { t: "住", r: "zhù", en: "to live (reside)", cats: ["verbs"] },
        { t: "去", r: "qù", en: "to go", cats: ["verbs"] },
        { t: "知道", r: "zhīdào", en: "to know", cats: ["verbs"] },
        { t: "每天", r: "měitiān", en: "every day", cats: ["vocabulary"] },
        { t: "家", r: "jiā", en: "home / family", cats: ["nouns"] },
      ],
      sentences: [
        { t: "我会说一点中文。", r: "wǒ huì shuō yìdiǎn Zhōngwén", en: "I can speak a little Chinese.", cats: ["verbs"], tok: ["我", "会", "说", "一点", "中文", "。"] },
        { t: "我每天工作。", r: "wǒ měitiān gōngzuò", en: "I work every day.", cats: ["verbs", "wordorder"], tok: ["我", "每天", "工作", "。"] },
        { t: "我不知道。", r: "wǒ bù zhīdào", en: "I don't know.", cats: ["negation"], tok: ["我", "不", "知道", "。"] },
        { t: "你住在哪里？", r: "nǐ zhù zài nǎlǐ?", en: "Where do you live?", cats: ["questions", "particles"], tok: ["你", "住", "在", "哪里", "？"] },
      ],
      dialogue: { title: "Small talk", turns: [
        { s: "A", t: "你在哪里工作？", r: "nǐ zài nǎlǐ gōngzuò?", en: "Where do you work?" },
        { s: "B", t: "我在医院工作。你呢？", r: "wǒ zài yīyuàn gōngzuò. nǐ ne?", en: "I work in a hospital. You?" },
        { s: "A", t: "我在家工作和学习。", r: "wǒ zài jiā gōngzuò hé xuéxí", en: "I work and study at home." },
        { s: "B", t: "太好了！我也在学中文。", r: "tài hǎo le! wǒ yě zài xué Zhōngwén", en: "Great! I'm also learning Chinese." },
      ]},
    },
    {
      id: "u6", title: "Getting Around", level: "A2",
      notes: [
        { title: "在哪里? — asking where", cat: "questions",
          body: "…在哪里? (zài nǎlǐ?) = where is…? Answer with 在 + place. 右边 (yòubian) = right side, 左边 (zuǒbian) = left, 一直走 (yìzhí zǒu) = go straight.",
          examples: [{ t: "车站在哪里？", r: "chēzhàn zài nǎlǐ?", en: "Where is the station?" }] },
      ],
      vocab: [
        { t: "路", r: "lù", en: "road", cats: ["nouns"] },
        { t: "车站", r: "chēzhàn", en: "station", cats: ["nouns"] },
        { t: "银行", r: "yínháng", en: "bank", cats: ["nouns"] },
        { t: "右边", r: "yòubian", en: "right side", cats: ["particles"] },
        { t: "左边", r: "zuǒbian", en: "left side", cats: ["particles"] },
        { t: "近", r: "jìn", en: "near", cats: ["particles"] },
        { t: "远", r: "yuǎn", en: "far", cats: ["particles"] },
        { t: "这里", r: "zhèlǐ", en: "here", cats: ["vocabulary"] },
      ],
      sentences: [
        { t: "车站在哪里？", r: "chēzhàn zài nǎlǐ?", en: "Where is the station?", cats: ["questions"], tok: ["车站", "在", "哪里", "？"] },
        { t: "离这里很近。", r: "lí zhèlǐ hěn jìn", en: "It's very near here.", cats: ["particles"], tok: ["离", "这里", "很", "近", "。"] },
        { t: "往右拐。", r: "wǎng yòu guǎi", en: "Turn right.", cats: ["verbs"], tok: ["往", "右", "拐", "。"] },
        { t: "银行很远。", r: "yínháng hěn yuǎn", en: "The bank is far.", cats: ["wordorder"], tok: ["银行", "很", "远", "。"] },
      ],
      dialogue: { title: "Asking for directions", turns: [
        { s: "A", t: "请问，银行在哪里？", r: "qǐngwèn, yínháng zài nǎlǐ?", en: "Excuse me, where is the bank?" },
        { s: "B", t: "一直走，然后往左拐。", r: "yìzhí zǒu, ránhòu wǎng zuǒ guǎi", en: "Go straight, then turn left." },
        { s: "A", t: "远吗？", r: "yuǎn ma?", en: "Is it far?" },
        { s: "B", t: "不远，很近。", r: "bù yuǎn, hěn jìn", en: "Not far, very close." },
      ]},
    },
  ],
};
