window.LISAN_COURSES = window.LISAN_COURSES || {};
window.LISAN_COURSES.es = {
  id: "es",
  intro: "Spanish is one of the most learner-friendly major languages: phonetic spelling, familiar alphabet, and huge amounts of free media.",
  units: [
    {
      id: "u1", title: "First Contact", level: "A0",
      notes: [
        { title: "Pronunciation basics", cat: "pronunciation",
          body: "Spanish is written the way it sounds. Vowels are always short and pure: a-e-i-o-u = ah-eh-ee-oh-oo. 'H' is silent, 'ñ' = ny, 'll' ≈ y, and 'j' is a raspy h.",
          examples: [{ t: "hola", en: "hello — the h is silent: OH-la" }, { t: "mañana", en: "tomorrow — man-YA-na" }] },
        { title: "Two ways to say 'you'", cat: "politeness",
          body: "Use 'tú' with friends and family; 'usted' with strangers, elders and in formal settings. 'Usted' uses the same verb form as he/she.",
          examples: [{ t: "¿Cómo estás?", en: "How are you? (informal)" }, { t: "¿Cómo está usted?", en: "How are you? (formal)" }] },
      ],
      vocab: [
        { t: "hola", en: "hello", cats: ["greetings"] },
        { t: "adiós", en: "goodbye", cats: ["greetings"] },
        { t: "buenos días", en: "good morning", cats: ["greetings"] },
        { t: "buenas noches", en: "good night", cats: ["greetings"] },
        { t: "por favor", en: "please", cats: ["politeness"] },
        { t: "gracias", en: "thank you", cats: ["politeness"] },
        { t: "sí", en: "yes", cats: ["vocabulary"] },
        { t: "no", en: "no", cats: ["vocabulary", "negation"] },
        { t: "perdón", en: "excuse me / sorry", cats: ["politeness"] },
        { t: "me llamo...", en: "my name is...", cats: ["greetings"] },
      ],
      sentences: [
        { t: "Hola, me llamo Ana.", en: "Hello, my name is Ana.", cats: ["greetings", "wordorder"] },
        { t: "Mucho gusto.", en: "Nice to meet you.", cats: ["greetings", "politeness"] },
        { t: "¿Cómo te llamas?", en: "What is your name?", cats: ["questions"] },
        { t: "Gracias, muy amable.", en: "Thank you, very kind.", cats: ["politeness"] },
      ],
      dialogue: { title: "Meeting someone", turns: [
        { s: "A", t: "¡Hola! ¿Cómo te llamas?", en: "Hi! What's your name?" },
        { s: "B", t: "Me llamo Sara. ¿Y tú?", en: "My name is Sara. And you?" },
        { s: "A", t: "Me llamo Leo. Mucho gusto.", en: "I'm Leo. Nice to meet you." },
        { s: "B", t: "Igualmente. ¡Adiós!", en: "Likewise. Bye!" },
      ]},
    },
    {
      id: "u2", title: "People & Pronouns", level: "A1",
      notes: [
        { title: "Subject pronouns & 'ser'", cat: "pronouns",
          body: "yo (I), tú (you), él/ella (he/she), nosotros (we), ellos (they). The verb 'ser' (to be): soy, eres, es, somos, son. Pronouns are usually dropped because the verb ending shows the person.",
          examples: [{ t: "Soy estudiante.", en: "I am a student. (no 'yo' needed)" }, { t: "Ella es doctora.", en: "She is a doctor." }] },
        { title: "Gender of nouns", cat: "nouns",
          body: "Every noun is masculine (el) or feminine (la). Words ending in -o are usually masculine, -a usually feminine. Adjectives match: amigo simpático / amiga simpática.",
          examples: [{ t: "el amigo / la amiga", en: "the (male/female) friend" }] },
      ],
      vocab: [
        { t: "yo", en: "I", cats: ["pronouns"] },
        { t: "tú", en: "you (informal)", cats: ["pronouns"] },
        { t: "él", en: "he", cats: ["pronouns"] },
        { t: "ella", en: "she", cats: ["pronouns"] },
        { t: "nosotros", en: "we", cats: ["pronouns"] },
        { t: "la familia", en: "the family", cats: ["nouns", "vocabulary"] },
        { t: "la madre", en: "the mother", cats: ["nouns"] },
        { t: "el padre", en: "the father", cats: ["nouns"] },
        { t: "el amigo", en: "the friend (m)", cats: ["nouns"] },
        { t: "ser", en: "to be", cats: ["verbs"] },
      ],
      sentences: [
        { t: "Yo soy de México.", en: "I am from Mexico.", cats: ["verbs", "pronouns"] },
        { t: "Ella es mi madre.", en: "She is my mother.", cats: ["verbs", "nouns"] },
        { t: "¿Quién es él?", en: "Who is he?", cats: ["questions", "pronouns"] },
        { t: "Somos amigos.", en: "We are friends.", cats: ["verbs", "wordorder"] },
      ],
      dialogue: { title: "Family photo", turns: [
        { s: "A", t: "¿Quién es ella?", en: "Who is she?" },
        { s: "B", t: "Es mi madre. Se llama Rosa.", en: "She's my mother. Her name is Rosa." },
        { s: "A", t: "¿Y él es tu padre?", en: "And is he your father?" },
        { s: "B", t: "Sí, y somos muy amigos.", en: "Yes, and we are very close." },
      ]},
    },
    {
      id: "u3", title: "Numbers & Time", level: "A1",
      notes: [
        { title: "Numbers 1–10", cat: "numbers",
          body: "uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez. For time use 'Es la una' (1 o'clock) but 'Son las dos/tres...' for 2+.",
          examples: [{ t: "Son las tres.", en: "It's three o'clock." }] },
        { title: "Asking the time", cat: "questions",
          body: "¿Qué hora es? = What time is it? Add 'y media' (half past) and 'y cuarto' (quarter past).",
          examples: [{ t: "Son las dos y media.", en: "It's half past two." }] },
      ],
      vocab: [
        { t: "uno", en: "one", cats: ["numbers"] },
        { t: "dos", en: "two", cats: ["numbers"] },
        { t: "tres", en: "three", cats: ["numbers"] },
        { t: "cinco", en: "five", cats: ["numbers"] },
        { t: "diez", en: "ten", cats: ["numbers"] },
        { t: "hoy", en: "today", cats: ["numbers", "vocabulary"] },
        { t: "mañana", en: "tomorrow", cats: ["numbers", "vocabulary"] },
        { t: "la hora", en: "the hour / time", cats: ["nouns", "numbers"] },
        { t: "el lunes", en: "Monday", cats: ["numbers"] },
        { t: "la semana", en: "the week", cats: ["nouns", "numbers"] },
      ],
      sentences: [
        { t: "¿Qué hora es?", en: "What time is it?", cats: ["questions", "numbers"] },
        { t: "Son las cinco.", en: "It's five o'clock.", cats: ["numbers"] },
        { t: "Hoy es lunes.", en: "Today is Monday.", cats: ["numbers", "wordorder"] },
        { t: "Tengo dos hermanos.", en: "I have two siblings.", cats: ["numbers", "verbs"] },
      ],
      dialogue: { title: "Making a plan", turns: [
        { s: "A", t: "¿Qué hora es?", en: "What time is it?" },
        { s: "B", t: "Son las cuatro y media.", en: "It's half past four." },
        { s: "A", t: "¿Nos vemos mañana a las diez?", en: "Shall we meet tomorrow at ten?" },
        { s: "B", t: "Sí, perfecto. ¡Hasta mañana!", en: "Yes, perfect. See you tomorrow!" },
      ]},
    },
    {
      id: "u4", title: "Food & Ordering", level: "A1",
      notes: [
        { title: "'Quiero' and 'quisiera'", cat: "politeness",
          body: "'Quiero' = I want. In a restaurant, 'quisiera' (I would like) or 'me gustaría' sounds more polite. Add 'por favor'.",
          examples: [{ t: "Quisiera un café, por favor.", en: "I'd like a coffee, please." }] },
        { title: "Plurals", cat: "nouns",
          body: "Add -s after vowels, -es after consonants. The article changes too: el taco → los tacos, la mesa → las mesas.",
          examples: [{ t: "dos cafés", en: "two coffees" }] },
      ],
      vocab: [
        { t: "el agua", en: "the water", cats: ["nouns", "vocabulary"] },
        { t: "el café", en: "the coffee", cats: ["nouns"] },
        { t: "el pan", en: "the bread", cats: ["nouns"] },
        { t: "la comida", en: "the food / meal", cats: ["nouns"] },
        { t: "querer", en: "to want", cats: ["verbs"] },
        { t: "comer", en: "to eat", cats: ["verbs"] },
        { t: "beber", en: "to drink", cats: ["verbs"] },
        { t: "la cuenta", en: "the bill", cats: ["nouns"] },
        { t: "rico", en: "tasty / delicious", cats: ["vocabulary"] },
        { t: "el restaurante", en: "the restaurant", cats: ["nouns"] },
      ],
      sentences: [
        { t: "Quisiera un café, por favor.", en: "I'd like a coffee, please.", cats: ["politeness", "verbs"] },
        { t: "¿Qué quieres comer?", en: "What do you want to eat?", cats: ["questions", "verbs"] },
        { t: "La comida está muy rica.", en: "The food is delicious.", cats: ["wordorder", "nouns"] },
        { t: "La cuenta, por favor.", en: "The bill, please.", cats: ["politeness"] },
      ],
      dialogue: { title: "At a café", turns: [
        { s: "A", t: "Buenos días. ¿Qué quiere tomar?", en: "Good morning. What would you like to drink?" },
        { s: "B", t: "Quisiera un café y pan, por favor.", en: "I'd like a coffee and bread, please." },
        { s: "A", t: "¿Algo más?", en: "Anything else?" },
        { s: "B", t: "No, gracias. La cuenta, por favor.", en: "No, thanks. The bill, please." },
      ]},
    },
    {
      id: "u5", title: "Daily Verbs", level: "A1+",
      notes: [
        { title: "Present tense of -ar verbs", cat: "verbs",
          body: "Drop -ar and add: -o, -as, -a, -amos, -an. hablar → hablo, hablas, habla, hablamos, hablan. Negation: put 'no' before the verb.",
          examples: [{ t: "No hablo francés.", en: "I don't speak French." }] },
      ],
      vocab: [
        { t: "hablar", en: "to speak", cats: ["verbs"] },
        { t: "trabajar", en: "to work", cats: ["verbs"] },
        { t: "estudiar", en: "to study", cats: ["verbs"] },
        { t: "vivir", en: "to live", cats: ["verbs"] },
        { t: "tener", en: "to have", cats: ["verbs"] },
        { t: "ir", en: "to go", cats: ["verbs"] },
        { t: "todos los días", en: "every day", cats: ["vocabulary"] },
        { t: "la casa", en: "the house", cats: ["nouns"] },
      ],
      sentences: [
        { t: "Hablo un poco de español.", en: "I speak a little Spanish.", cats: ["verbs"] },
        { t: "Trabajo todos los días.", en: "I work every day.", cats: ["verbs", "wordorder"] },
        { t: "No tengo tiempo hoy.", en: "I don't have time today.", cats: ["negation", "verbs"] },
        { t: "¿Dónde vives?", en: "Where do you live?", cats: ["questions", "verbs"] },
      ],
      dialogue: { title: "Small talk", turns: [
        { s: "A", t: "¿Dónde trabajas?", en: "Where do you work?" },
        { s: "B", t: "Trabajo en un hospital. ¿Y tú?", en: "I work in a hospital. And you?" },
        { s: "A", t: "Estudio y trabajo en casa.", en: "I study and work from home." },
        { s: "B", t: "¡Qué bien! Yo no estudio ahora.", en: "Nice! I'm not studying right now." },
      ]},
    },
    {
      id: "u6", title: "Getting Around", level: "A2",
      notes: [
        { title: "¿Dónde está...? — asking where", cat: "questions",
          body: "'Estar' (not 'ser') is used for location: está = it is (located). 'a la derecha / izquierda' = to the right/left, 'todo recto' = straight ahead.",
          examples: [{ t: "¿Dónde está la estación?", en: "Where is the station?" }] },
      ],
      vocab: [
        { t: "la calle", en: "the street", cats: ["nouns"] },
        { t: "la estación", en: "the station", cats: ["nouns"] },
        { t: "el banco", en: "the bank", cats: ["nouns"] },
        { t: "la derecha", en: "the right", cats: ["vocabulary"] },
        { t: "la izquierda", en: "the left", cats: ["vocabulary"] },
        { t: "cerca", en: "near", cats: ["particles"] },
        { t: "lejos", en: "far", cats: ["particles"] },
        { t: "aquí", en: "here", cats: ["vocabulary"] },
      ],
      sentences: [
        { t: "¿Dónde está la estación?", en: "Where is the station?", cats: ["questions", "verbs"] },
        { t: "Está cerca de aquí.", en: "It's near here.", cats: ["verbs", "particles"] },
        { t: "Gira a la derecha.", en: "Turn right.", cats: ["verbs", "wordorder"] },
        { t: "El banco está lejos.", en: "The bank is far.", cats: ["wordorder", "verbs"] },
      ],
      dialogue: { title: "Asking for directions", turns: [
        { s: "A", t: "Perdón, ¿dónde está el banco?", en: "Excuse me, where is the bank?" },
        { s: "B", t: "Todo recto y a la izquierda.", en: "Straight ahead and to the left." },
        { s: "A", t: "¿Está lejos?", en: "Is it far?" },
        { s: "B", t: "No, está muy cerca.", en: "No, it's very close." },
      ]},
    },
  ],
};
