window.LISAN_COURSES = window.LISAN_COURSES || {};
window.LISAN_COURSES.ur = {
  id: "ur",
  intro: "Urdu is written right-to-left in the Nastaliq script and shares its spoken core with Hindi. Every word here includes Roman Urdu so you can start speaking before mastering the script.",
  units: [
    {
      id: "u1", title: "First Contact", level: "A0",
      notes: [
        { title: "Script & sounds", cat: "script",
          body: "Urdu is written right-to-left. Key sounds: 'kh' (خ) as in Bach, 'gh' (غ) a gargled g, retroflex ṭ/ḍ (ٹ/ڈ) with the tongue curled back, and nasalized vowels (ں). Roman Urdu is shown for every word.",
          examples: [{ t: "خوش", r: "khush", en: "happy — kh as in Bach" }] },
        { title: "Politeness: آپ / تم", cat: "politeness",
          body: "'آپ' (aap) is the polite 'you' — safe with everyone. 'تم' (tum) is for friends. Verbs agree: aap kaise hain? vs tum kaise ho?",
          examples: [{ t: "آپ کیسے ہیں؟", r: "aap kaise hain?", en: "How are you? (polite)" }] },
      ],
      vocab: [
        { t: "السلام علیکم", r: "assalam-o-alaikum", en: "hello (peace be upon you)", cats: ["greetings"] },
        { t: "خدا حافظ", r: "khuda hafiz", en: "goodbye", cats: ["greetings"] },
        { t: "صبح بخیر", r: "subah bakhair", en: "good morning", cats: ["greetings"] },
        { t: "شب بخیر", r: "shab bakhair", en: "good night", cats: ["greetings"] },
        { t: "مہربانی", r: "meherbani", en: "please / kindness", cats: ["politeness"] },
        { t: "شکریہ", r: "shukriya", en: "thank you", cats: ["politeness"] },
        { t: "جی ہاں", r: "ji haan", en: "yes (polite)", cats: ["vocabulary", "politeness"] },
        { t: "نہیں", r: "nahin", en: "no", cats: ["vocabulary", "negation"] },
        { t: "معاف کیجیے", r: "maaf kijiye", en: "excuse me / sorry", cats: ["politeness"] },
        { t: "میرا نام ... ہے", r: "mera naam ... hai", en: "my name is...", cats: ["greetings"] },
      ],
      sentences: [
        { t: "میرا نام علی ہے۔", r: "mera naam Ali hai", en: "My name is Ali.", cats: ["greetings", "wordorder"] },
        { t: "آپ سے مل کر خوشی ہوئی۔", r: "aap se mil kar khushi hui", en: "Nice to meet you.", cats: ["politeness"] },
        { t: "آپ کا نام کیا ہے؟", r: "aap ka naam kya hai?", en: "What is your name?", cats: ["questions"] },
        { t: "بہت شکریہ۔", r: "bahut shukriya", en: "Thank you very much.", cats: ["politeness"] },
      ],
      dialogue: { title: "Meeting someone", turns: [
        { s: "A", t: "السلام علیکم! آپ کا نام کیا ہے؟", r: "assalam-o-alaikum! aap ka naam kya hai?", en: "Hello! What's your name?" },
        { s: "B", t: "میرا نام فاطمہ ہے۔ اور آپ کا؟", r: "mera naam Fatima hai. aur aap ka?", en: "My name is Fatima. And yours?" },
        { s: "A", t: "میرا نام احمد ہے۔ مل کر خوشی ہوئی۔", r: "mera naam Ahmed hai. mil kar khushi hui", en: "I'm Ahmed. Nice to meet you." },
        { s: "B", t: "مجھے بھی۔ خدا حافظ!", r: "mujhe bhi. khuda hafiz!", en: "Me too. Goodbye!" },
      ]},
    },
    {
      id: "u2", title: "People & Pronouns", level: "A1",
      notes: [
        { title: "Pronouns & ہونا (to be)", cat: "pronouns",
          body: "میں (main, I), تم (tum, you), آپ (aap, you polite), وہ (voh, he/she/that), ہم (hum, we). 'To be': main hoon, tum ho, aap hain, voh hai, hum hain. The verb always comes LAST.",
          examples: [{ t: "میں طالب علم ہوں۔", r: "main talib-e-ilm hoon", en: "I am a student." }] },
        { title: "Gender agreement", cat: "nouns",
          body: "Nouns and verbs have gender. 'mera' (my, m) vs 'meri' (my, f): mera bhai (my brother), meri behen (my sister). Male speakers say 'karta hoon', female 'karti hoon'.",
          examples: [{ t: "میرا بھائی / میری بہن", r: "mera bhai / meri behen", en: "my brother / my sister" }] },
      ],
      vocab: [
        { t: "میں", r: "main", en: "I", cats: ["pronouns"] },
        { t: "تم", r: "tum", en: "you (informal)", cats: ["pronouns"] },
        { t: "آپ", r: "aap", en: "you (polite)", cats: ["pronouns", "politeness"] },
        { t: "وہ", r: "voh", en: "he / she / that", cats: ["pronouns"] },
        { t: "ہم", r: "hum", en: "we", cats: ["pronouns"] },
        { t: "خاندان", r: "khandaan", en: "family", cats: ["nouns"] },
        { t: "امی", r: "ammi", en: "mom", cats: ["nouns"] },
        { t: "ابو", r: "abbu", en: "dad", cats: ["nouns"] },
        { t: "دوست", r: "dost", en: "friend", cats: ["nouns"] },
        { t: "کون", r: "kaun", en: "who", cats: ["questions"] },
      ],
      sentences: [
        { t: "میں لاہور سے ہوں۔", r: "main Lahore se hoon", en: "I am from Lahore.", cats: ["pronouns", "particles"] },
        { t: "وہ میری امی ہیں۔", r: "voh meri ammi hain", en: "She is my mother.", cats: ["nouns", "politeness"] },
        { t: "یہ کون ہے؟", r: "yeh kaun hai?", en: "Who is this?", cats: ["questions"] },
        { t: "ہم دوست ہیں۔", r: "hum dost hain", en: "We are friends.", cats: ["wordorder"] },
      ],
      dialogue: { title: "Family photo", turns: [
        { s: "A", t: "یہ کون ہیں؟", r: "yeh kaun hain?", en: "Who is this? (respectful)" },
        { s: "B", t: "یہ میری امی ہیں۔", r: "yeh meri ammi hain", en: "This is my mother." },
        { s: "A", t: "اور یہ آپ کے ابو ہیں؟", r: "aur yeh aap ke abbu hain?", en: "And is this your father?" },
        { s: "B", t: "جی ہاں، یہ میرے ابو ہیں۔", r: "ji haan, yeh mere abbu hain", en: "Yes, this is my father." },
      ]},
    },
    {
      id: "u3", title: "Numbers & Time", level: "A1",
      notes: [
        { title: "Numbers 1–10", cat: "numbers",
          body: "ایک (ek), دو (do), تین (teen), چار (chaar), پانچ (paanch), چھ (chhe), سات (saat), آٹھ (aath), نو (nau), دس (das).",
          examples: [{ t: "تین بجے ہیں۔", r: "teen baje hain", en: "It's three o'clock." }] },
        { title: "Asking the time", cat: "questions",
          body: "کتنے بجے ہیں؟ (kitne baje hain?) = What time is it? 'baje' = o'clock. ساڑھے (saarhe) = half past: saarhe teen = 3:30.",
          examples: [{ t: "ساڑھے چار بجے ہیں۔", r: "saarhe chaar baje hain", en: "It's half past four." }] },
      ],
      vocab: [
        { t: "ایک", r: "ek", en: "one", cats: ["numbers"] },
        { t: "دو", r: "do", en: "two", cats: ["numbers"] },
        { t: "تین", r: "teen", en: "three", cats: ["numbers"] },
        { t: "پانچ", r: "paanch", en: "five", cats: ["numbers"] },
        { t: "دس", r: "das", en: "ten", cats: ["numbers"] },
        { t: "آج", r: "aaj", en: "today", cats: ["vocabulary", "numbers"] },
        { t: "کل", r: "kal", en: "tomorrow / yesterday", cats: ["vocabulary", "numbers"] },
        { t: "وقت", r: "waqt", en: "time", cats: ["nouns", "numbers"] },
        { t: "پیر", r: "peer", en: "Monday", cats: ["numbers"] },
        { t: "ہفتہ", r: "hafta", en: "week / Saturday", cats: ["nouns", "numbers"] },
      ],
      sentences: [
        { t: "کتنے بجے ہیں؟", r: "kitne baje hain?", en: "What time is it?", cats: ["questions", "numbers"] },
        { t: "پانچ بجے ہیں۔", r: "paanch baje hain", en: "It's five o'clock.", cats: ["numbers"] },
        { t: "آج پیر ہے۔", r: "aaj peer hai", en: "Today is Monday.", cats: ["numbers", "wordorder"] },
        { t: "میرے دو بھائی ہیں۔", r: "mere do bhai hain", en: "I have two brothers.", cats: ["numbers"] },
      ],
      dialogue: { title: "Making a plan", turns: [
        { s: "A", t: "کتنے بجے ہیں؟", r: "kitne baje hain?", en: "What time is it?" },
        { s: "B", t: "ساڑھے چار بجے ہیں۔", r: "saarhe chaar baje hain", en: "It's half past four." },
        { s: "A", t: "کل دس بجے ملتے ہیں؟", r: "kal das baje milte hain?", en: "Shall we meet tomorrow at ten?" },
        { s: "B", t: "جی، بہت اچھا۔ کل ملیں گے!", r: "ji, bahut acha. kal milenge!", en: "Yes, very good. See you tomorrow!" },
      ]},
    },
    {
      id: "u4", title: "Food & Ordering", level: "A1",
      notes: [
        { title: "چاہیے — I want/need", cat: "politeness",
          body: "'مجھے ... چاہیے' (mujhe ... chahiye) = I want/need... Very useful everywhere. Politer: 'دیجیے' (dijiye) = please give.",
          examples: [{ t: "مجھے پانی چاہیے۔", r: "mujhe paani chahiye", en: "I need water." }, { t: "ایک چائے دیجیے۔", r: "ek chai dijiye", en: "Please give (me) one tea." }] },
        { title: "SOV word order", cat: "wordorder",
          body: "Urdu is Subject-Object-Verb: میں کھانا کھاتا ہوں = I food eat. The verb 'hai/hain/hoon' always closes the sentence.",
          examples: [{ t: "میں چائے پیتا ہوں۔", r: "main chai peeta hoon", en: "I drink tea. (m. speaker)" }] },
      ],
      vocab: [
        { t: "پانی", r: "paani", en: "water", cats: ["nouns"] },
        { t: "چائے", r: "chai", en: "tea", cats: ["nouns"] },
        { t: "روٹی", r: "roti", en: "bread / roti", cats: ["nouns"] },
        { t: "کھانا", r: "khaana", en: "food / to eat", cats: ["nouns", "verbs"] },
        { t: "پینا", r: "peena", en: "to drink", cats: ["verbs"] },
        { t: "چاہیے", r: "chahiye", en: "want / need", cats: ["verbs"] },
        { t: "بل", r: "bill", en: "the bill", cats: ["nouns"] },
        { t: "مزیدار", r: "mazedaar", en: "delicious", cats: ["vocabulary"] },
        { t: "ہوٹل", r: "hotel", en: "restaurant (hotel)", cats: ["nouns"] },
        { t: "اور", r: "aur", en: "and / more", cats: ["particles"] },
      ],
      sentences: [
        { t: "مجھے ایک چائے چاہیے۔", r: "mujhe ek chai chahiye", en: "I want one tea.", cats: ["politeness", "wordorder"] },
        { t: "آپ کیا کھانا چاہتے ہیں؟", r: "aap kya khaana chahte hain?", en: "What would you like to eat?", cats: ["questions", "verbs"] },
        { t: "کھانا بہت مزیدار ہے۔", r: "khaana bahut mazedaar hai", en: "The food is very delicious.", cats: ["wordorder"] },
        { t: "بل دیجیے۔", r: "bill dijiye", en: "Please give the bill.", cats: ["politeness"] },
      ],
      dialogue: { title: "At a tea stall", turns: [
        { s: "A", t: "جی، کیا چاہیے؟", r: "ji, kya chahiye?", en: "Yes, what would you like?" },
        { s: "B", t: "ایک چائے اور روٹی دیجیے۔", r: "ek chai aur roti dijiye", en: "Please give one tea and roti." },
        { s: "A", t: "اور کچھ؟", r: "aur kuch?", en: "Anything else?" },
        { s: "B", t: "نہیں، شکریہ۔ بل دیجیے۔", r: "nahin, shukriya. bill dijiye", en: "No, thanks. The bill, please." },
      ]},
    },
    {
      id: "u5", title: "Daily Verbs", level: "A1+",
      notes: [
        { title: "Present habitual: کرتا ہوں", cat: "verbs",
          body: "Verb stem + ta/ti/te + hoon/ho/hai: main kaam karta hoon (I work, m.) / karti hoon (f.). Negation: 'نہیں' before the verb: main nahin jaanta.",
          examples: [{ t: "میں ہر روز کام کرتا ہوں۔", r: "main har roz kaam karta hoon", en: "I work every day. (m.)" }] },
      ],
      vocab: [
        { t: "بولنا", r: "bolna", en: "to speak", cats: ["verbs"] },
        { t: "کام کرنا", r: "kaam karna", en: "to work", cats: ["verbs"] },
        { t: "سیکھنا", r: "seekhna", en: "to learn", cats: ["verbs"] },
        { t: "رہنا", r: "rehna", en: "to live / stay", cats: ["verbs"] },
        { t: "جانا", r: "jaana", en: "to go", cats: ["verbs"] },
        { t: "جاننا", r: "jaanna", en: "to know", cats: ["verbs"] },
        { t: "ہر روز", r: "har roz", en: "every day", cats: ["vocabulary"] },
        { t: "گھر", r: "ghar", en: "house / home", cats: ["nouns"] },
      ],
      sentences: [
        { t: "میں تھوڑی اردو بولتا ہوں۔", r: "main thori Urdu bolta hoon", en: "I speak a little Urdu. (m.)", cats: ["verbs"] },
        { t: "میں ہر روز کام کرتی ہوں۔", r: "main har roz kaam karti hoon", en: "I work every day. (f.)", cats: ["verbs"] },
        { t: "میں نہیں جانتا۔", r: "main nahin jaanta", en: "I don't know. (m.)", cats: ["negation", "verbs"] },
        { t: "آپ کہاں رہتے ہیں؟", r: "aap kahan rehte hain?", en: "Where do you live?", cats: ["questions", "verbs"] },
      ],
      dialogue: { title: "Small talk", turns: [
        { s: "A", t: "آپ کہاں کام کرتے ہیں؟", r: "aap kahan kaam karte hain?", en: "Where do you work?" },
        { s: "B", t: "میں ہسپتال میں کام کرتا ہوں۔ اور آپ؟", r: "main haspatal mein kaam karta hoon. aur aap?", en: "I work in a hospital. And you?" },
        { s: "A", t: "میں گھر سے کام کرتا ہوں۔", r: "main ghar se kaam karta hoon", en: "I work from home." },
        { s: "B", t: "بہت خوب! میں اردو سیکھ رہا ہوں۔", r: "bahut khoob! main Urdu seekh raha hoon", en: "Excellent! I am learning Urdu." },
      ]},
    },
    {
      id: "u6", title: "Getting Around", level: "A2",
      notes: [
        { title: "کہاں ہے؟ — asking where", cat: "questions",
          body: "'... کہاں ہے؟' (kahan hai?) = where is...? 'دائیں / بائیں' (daayen/baayen) = right/left, 'سیدھا' (seedha) = straight, 'قریب' (qareeb) = near.",
          examples: [{ t: "اسٹیشن کہاں ہے؟", r: "station kahan hai?", en: "Where is the station?" }] },
      ],
      vocab: [
        { t: "سڑک", r: "sarak", en: "road / street", cats: ["nouns"] },
        { t: "اسٹیشن", r: "station", en: "station", cats: ["nouns"] },
        { t: "بینک", r: "bank", en: "bank", cats: ["nouns"] },
        { t: "دائیں", r: "daayen", en: "right", cats: ["particles"] },
        { t: "بائیں", r: "baayen", en: "left", cats: ["particles"] },
        { t: "قریب", r: "qareeb", en: "near", cats: ["particles"] },
        { t: "دور", r: "duur", en: "far", cats: ["particles"] },
        { t: "یہاں", r: "yahan", en: "here", cats: ["vocabulary"] },
      ],
      sentences: [
        { t: "اسٹیشن کہاں ہے؟", r: "station kahan hai?", en: "Where is the station?", cats: ["questions"] },
        { t: "یہ یہاں سے قریب ہے۔", r: "yeh yahan se qareeb hai", en: "It's near here.", cats: ["particles"] },
        { t: "دائیں مڑیے۔", r: "daayen muriye", en: "Turn right. (polite)", cats: ["verbs", "politeness"] },
        { t: "بینک دور ہے۔", r: "bank duur hai", en: "The bank is far.", cats: ["wordorder"] },
      ],
      dialogue: { title: "Asking for directions", turns: [
        { s: "A", t: "معاف کیجیے، بینک کہاں ہے؟", r: "maaf kijiye, bank kahan hai?", en: "Excuse me, where is the bank?" },
        { s: "B", t: "سیدھا جائیے، پھر بائیں۔", r: "seedha jaiye, phir baayen", en: "Go straight, then left." },
        { s: "A", t: "کیا وہ دور ہے؟", r: "kya voh duur hai?", en: "Is it far?" },
        { s: "B", t: "نہیں، بہت قریب ہے۔", r: "nahin, bahut qareeb hai", en: "No, it's very near." },
      ]},
    },
  ],
};
